import scrapy

class ZillowItem(scrapy.Item):
    zpid = scrapy.Field()
    streetAddress = scrapy.Field()
    zipcode = scrapy.Field()
    city = scrapy.Field()
    state = scrapy.Field()
    latitude = scrapy.Field()
    longitude = scrapy.Field()
    price = scrapy.Field()
    dateSold = scrapy.Field()
    bathrooms = scrapy.Field()
    bedrooms = scrapy.Field()
    livingArea = scrapy.Field()
    homeType = scrapy.Field()
    taxAssessedValue = scrapy.Field()
    lotAreaValue = scrapy.Field()
    lotAreaUnit = scrapy.Field()
    monthlyZestimate = scrapy.Field()
    listing_type = scrapy.Field()
